### ISSUE TITLE
Explain how to name extra-requirements file and keys when implementing a new benchmark

### ISSUE THREAD

**Issue by KEggensperger** [automl/HPOBench#110]
see title; Add info to HowToAddNewBenchmark

**Comment by renesass** [comment]
Can you have a look and verify everything? I also added some todos which has to be fixed.

**Comment by KEggensperger** [comment]
Nice, thanks a lot! Overall, this looks great and definitely improves the manual.

#### Specific comments

  * l5 <type>: Category of the benchmark, e.g. od (outlier detection) --> outlier detection is an unfortunate example of a type, please change that to "ml, rl, nas"
  * l7/8 filename "<type>_ocsvm" or "<type>_OCSVM" --> if type is ml, rl, nas this does not need to be part of the filename since it is already clear from the path what the type of the benchmark is, also here, please use a more toy example, e.g. just "SVM"
  * l15 Can you make "Fork" a link to https://docs.github.com/en/get-started/quickstart/fork-a-repo
  * l26 Please make sure, that the filename is consistent with l7
  * l33 Consider fixing the version of each dependency to maintain reproducibility. --> Make sure to also note the exact version of each dependency.
  * l34 "Add dependencies installable via `pip` in a new file to `/extra_requirements`. While the name of the file is secondary, please choose a descriptive name. Add the dependencies as a list under the key `<new_benchmark>`."
  * l52-58 Please add some more info, maybe even with some code showing how to set keys/strings.

#### General Comments
We should link to this in the main Readme file. Could you please update the section in the first paragraph?

**Comment by renesass** [comment]
I changed most of your comments. However, I don't know what else I should add to l52-58.

**Comment by KEggensperger** [comment]
Looks good. Looking at it again, I agree that all information regarding how to create the container class is actually already in the text. Thanks a lot, I'll close this issue then.
