### ISSUE TITLE
Singularity installation

### ISSUE THREAD

**Issue by ArlindKadra** [automl/HPOBench#123]
Hey all,

Personally I faced quite a few problems with the singularity installation, which could not find the go installation by following the 3.5 singularity installation guide. Following the issues at the singularity repo, they now suggest following the latest documentation:
https://singularity.hpcng.org/admin-docs/master/installation.html

With the latest installation guide I managed to get it to work and it worked with your benchmarks too, as such maybe you can update the README with the link above, so that other users do not face the singularity related issue.

**Comment by PhMueller** [comment]
Hey Arlind, 

thanks for providing your solution. 
We will update the docs accordingly.

@KEggensperger: Version 3.8 was released 2 months ago, we could add a test for this version to the Github actions.
