### ISSUE TITLE
Wiki does not have any URLs to link to the source of each benchmark

### ISSUE THREAD

**Issue by nabenabe0928** [automl/HPOBench#129]
[Here](https://github.com/nabenabe0928/HPOBench/blob/doc-add-url-and-info-of-benchmark/Available-Containerized-Benchmarks.md), I added the linked version of the wiki.

**Comment by KEggensperger** [comment]
Thanks a lot. I re-organized the information and created https://github.com/automl/HPOBench/wiki/Available-Containerized-Benchmarks and https://github.com/automl/HPOBench/wiki/Benchmarks-used-for-%60HPOBench:-A-Collection-of-Reproducible-Multi-Fidelity-Benchmark-Problems-for-HPO%60 which should have the information you provided.
