### ISSUE TITLE
The documentation string about the seed of NASBench201 is misleading

### ISSUE THREAD

**Issue by nabenabe0928** [automl/HPOBench#138]
NASBench201 has only two of the seeds (777, 888) for almost half of the architectures as mentioned [here](https://github.com/D-X-Y/NATS-Bench/issues/30).

On the other hand, HPOBench is saying three seeds (777, 888, 999) are available.
For this reason, I checked one index, i.e. 347, of the seed 999 that is not held by NASBench201.
Then, I just found out that the seed 888 is used to patch the results for the seed 999.

First, my question:
HPOBench also provides two seeds for most architectures, right?

Request:
Could you make a notice about this matter if the answer to my question is yes?

**Comment by KEggensperger** [comment]
Thanks for raising this. I believe this is true and should be mentioned in the docs. @PhMueller Could you please add a note to the [wiki](https://github.com/automl/HPOBench/wiki/Available-Containerized-Benchmarks) for all benchmarks where this applies?
