### ISSUE TITLE
Implementation of Optimizers

### ISSUE THREAD

**Issue by drpriscu** [automl/HPOBench#139]
According to the paper, "HPOBench: A Collection of Reproducible Multi-Fidelity Benchmark Problems for HPO”, the BO (KDE) optimizer was implemented using the HpBandSter codebase. May I ask if this means you used the HpBandSter package's 'h2bo' optimizer? Furthermore, the DE optimiser was also implemented. Please could you confirm if this was achieved by calling the 'DE' optimizer from the DEHB repository?

**Comment by KEggensperger** [comment]
Hi @drpriscu, 

Thanks for your questions. 

No, we did not use the h2bo optimizer for this. Regarding DE, Yes, we used the implementation from the DEHB repository. We also released the code we used to run experiments [here](https://github.com/automl/HPOBenchExperimentUtils).
