### ISSUE TITLE
Where to find the best-known values of all benchmarks?

### ISSUE THREAD

**Issue by tyf0416** [automl/HPOBench#158]
I am trying to study the benchmark library and test some customized optimizers according to the same framework you have published. But I am wondering where could I find the best-known values of all benchmarks applied in the paper "HPOBench: A Collection of Reproducible Multi-Fidelity Benchmark Problems for HPO"? Are they accessible in the experimental code, or somewhere?
Hope for your message.

**Comment by Neeratyoy** [comment]
Hi,
The best-known value or the optimum is only available for the [TabularBenchmarks](https://github.com/automl/HPOBench/blob/master/hpobench/benchmarks/ml/tabular_benchmark.py#L40).

**Comment by KEggensperger** [comment]
And for the remaining benchmarks, these values are in the experiment code and can be found [here](https://github.com/automl/HPOBenchExperimentUtils/blob/master/HPOBenchExperimentUtils/utils/plotting_utils.py) (with some comments on how we obtained them).

**Comment by PhMueller** [comment]
Maybe it is a good idea to store the best available values (if available) in the benchmark or somewhere in the readme? @KEggensperger 

The latter would be easier for now.

**Comment by KEggensperger** [comment]
I added it to the [wiki](https://github.com/automl/HPOBench/wiki/Benchmarks-used-for-%60HPOBench:-A-Collection-of-Reproducible-Multi-Fidelity-Benchmark-Problems-for-HPO%60) page where we list benchmarks used for the paper.

**Comment by Neeratyoy** [comment]
To expound on the above:
For all _tabular_ Community Benchmarks (primarily the NAS benchmarks) and the new _ML_ Tabular benchmarks, we have the optimum recorded.
For reference, you can refer to the wiki page links (comment above) to the experiment repositories (for our paper) where we assumed a certain optimum for the other benchmarks as the best from multiple runs.

**Comment by tyf0416** [comment]
Thanks for the responses. Those solved my question.
