### ISSUE TITLE
Cleaning up old containers through the API

### ISSUE THREAD

**Issue by Game4Move78** [automl/HPOBench#175]
Is there any way to properly dispose of containers when doing multiple runs? At the moment I just call `del benchmark` and instantiate a new one with a different seed, but it leaves a lot of dangling containers that have to be manually cleaned up with `singularity instance stop -a`.

**Comment by KEggensperger** [comment]
Hi there. I believe calling `benchmark._shutdown()` should stop the instance immediately (see https://github.com/automl/HPOBench/blob/master/hpobench/container/client_abstract_benchmark.py#L481)

**Comment by Game4Move78** [comment]
Thank you. This appears to solve my problem.
