### ISSUE TITLE
HPOBench containers set root logger level when importing

### ISSUE THREAD

**Issue by Game4Move78** [automl/HPOBench#176]
https://github.com/automl/HPOBench/blob/d8b45b1eca9a61c63fe79cdfbe509f77d3f5c779/hpobench/container/client_abstract_benchmark.py#L45

If a program sets all loggers to a particular log level and then imports a HPOBench container later in the program (i.e. at the function level to make the dependency on hpobench optional), it will override their chosen log settings. This is because the root logger is set by HPOBench. Shouldn't it be:

```python
root = logging.getLogger("hpobench")
root.setLevel(level=LOG_LEVEL)
```

**Comment by Neeratyoy** [comment]
Thanks for pointing this out.
Have addressed them [here](https://github.com/automl/HPOBench/commit/47bf141f79e6bdfb26d1f1218b5d5aac09d7d2ce) on the `master` branch directly.

This should not break anything or affect your usage I believe. Please feel free to close the issue if this resolved it.
