### ISSUE TITLE
Permission denied? 

### ISSUE THREAD

**Issue by Husam94** [automl/HPOBench#183]
Hi, I've tried running the SliceLocalizationBenchmark example (the first one on the main page) and it returns the following error: [I've tried both the master and the dev branch] 

[INFO] BenchmarkClient at 2023-10-08 11:57:17,957 --- ~~~ HPOBENCH VERSION: 0.0.11dev ~~~~ CONTAINER VERSION: 0.0.5 ~~~
[INFO] BenchmarkClient at 2023-10-08 11:57:17,959 --- Start downloading the container tabular_benchmarks_0.0.5 from oras://gitlab.tf.uni-freiburg.de:5050/muelleph/hpobench-registry. This may take several minutes.
/bin/sh: 1: singularity: Permission denied
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[3], line 2
      1 from hpobench.container.benchmarks.nas.tabular_benchmarks import SliceLocalizationBenchmark
----> 2 b = SliceLocalizationBenchmark(rng=1)
      3 config = b.get_configuration_space(seed=1).sample_configuration()
      4 result_dict = b.objective_function(configuration=config, fidelity={"budget": 100}, rng=1)

File ~/miniconda3/lib/python3.11/site-packages/hpobench/container/benchmarks/nas/tabular_benchmarks.py:15, in SliceLocalizationBenchmark.__init__(self, **kwargs)
     13 kwargs['container_name'] = kwargs.get('container_name', 'tabular_benchmarks')
     14 kwargs['latest'] = kwargs.get('container_tag', '0.0.5')
---> 15 super(SliceLocalizationBenchmark, self).__init__(**kwargs)

File ~/miniconda3/lib/python3.11/site-packages/hpobench/container/client_abstract_benchmark.py:129, in AbstractBenchmarkClient.__init__(self, benchmark_name, container_name, container_source, container_tag, env_str, bind_str, gpu, rng, socket_id, **kwargs)
    126 if not self.proxy_only:
    127     self.socket_id = self._id_generator()
--> 129     self.load_benchmark(benchmark_name=benchmark_name, container_name=container_name,
    130                         container_source=container_source, container_tag=container_tag, **kwargs)
    131     self.start_server(benchmark_name=benchmark_name, env_str=env_str, bind_str=bind_str, gpu=gpu)
    132     self.connect_to_server()

File ~/miniconda3/lib/python3.11/site-packages/hpobench/container/client_abstract_benchmark.py:238, in AbstractBenchmarkClient.load_benchmark(self, benchmark_name, container_name, container_source, container_tag, **kwargs)
    235         else:
    236             logger.debug('Skipping downloading the container. It is already downloaded.')
--> 238     download_container(self.container_dir, container_name, self.container_source, container_tag)
    239 else:
    240     logger.debug(f'Looking on the local filesystem for the container file, since container source was '
    241                  f'either \'None\' or not a known address. Image Source: {self.container_source}')

File ~/miniconda3/lib/python3.11/site-packages/oslo_concurrency/lockutils.py:414, in synchronized.<locals>.wrap.<locals>.inner(*args, **kwargs)
    408         t2 = timeutils.now()
    409         LOG.debug('Lock "%(name)s" acquired by "%(function)s" :: '
    410                   'waited %(wait_secs)0.3fs',
    411                   {'name': name,
    412                    'function': f_name,
    413                    'wait_secs': (t2 - t1)})
--> 414         return f(*args, **kwargs)
    415 except AcquireLockFailedException:
    416     gotten = False

File ~/miniconda3/lib/python3.11/site-packages/hpobench/container/client_abstract_benchmark.py:233, in AbstractBenchmarkClient.load_benchmark.<locals>.download_container(container_dir, container_name, container_source, container_tag)
    230     logger.info(f'Start downloading the container {self.container_name_with_tag} '
    231                 f'from {container_source}. This may take several minutes.')
    232     logger.debug(cmd)
--> 233     subprocess.run(cmd, shell=True, check=True)
    234     time.sleep(1)
    235 else:

File ~/miniconda3/lib/python3.11/subprocess.py:571, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    569     retcode = process.poll()
    570     if check and retcode:
--> 571         raise CalledProcessError(retcode, process.args,
    572                                  output=stdout, stderr=stderr)
    573 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command 'singularity pull --dir /home/husam/.cache/hpobench/hpobench-1000 --name tabular_benchmarks_0.0.5 oras://gitlab.tf.uni-freiburg.de:5050/muelleph/hpobench-registry/tabular_benchmarks/0.0.5:latest' returned non-zero exit status 127.

**Comment by Neeratyoy** [comment]
Hi,

Can you please describe your setup in more detail such as the OS, the Python version, if you have Singularity installed, etc.?

I created a new environment on a Linux machine with Python `3.9.18`, ran `pip install -e .` on the master branch, and was able to successfully run the example:
```python
from hpobench.container.benchmarks.nas.tabular_benchmarks import SliceLocalizationBenchmark
b = SliceLocalizationBenchmark(rng=1)
```

On a Mac, when doing the same thing, I get an error and stack trace like you shared. Perhaps the issue is with Singularity that needs fixing at your end?

**Comment by Husam94** [comment]
Hey, I reinstalled everything on a fresh instance and it works. Sorry for the bother!
