### ISSUE TITLE
Check fidelity space wrapper: Handle unknown keys in fidelity dict

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOBench#35]
The wrapper function misses handling any keys that are present in the dictionary passed in the keyword argument `fidelity` that are not members of the benchmark's fidelity space. These cases should at the very least cause a warning to be raised.

One easy fix is to change `fidelity.get` to `fidelity.pop` [here](https://github.com/automl/HPOlib2/blob/674e93e395dfd2cdb3ea0c8dad4a4ec3cf880b1e/hpolib/abstract_benchmark.py#L162), and check if fidelity is now empty. The broader question is, should this use-case raise a warning or an error?

**Comment by PhMueller** [comment]
Thats a good point.

IMO an error would be better. Because if there is something in the fidelity dict which cannot be parsed, this would indicate a typo in the fidelity name or another strange error. 

The idea with the dict.pop is fine. I will include it in the next version. Thanks!

**Comment by KEggensperger** [comment]
I replaced the fidelity.pop() with fidelity.get() since this empties the dictionary given by the user. This could lead to strange behaviour if the user wants to use the dictionary for more function calls. If we want to use pop(), please create a copy of the dictionary beforehand.
