### ISSUE TITLE
where is synthetic_functions?

### ISSUE THREAD

**Issue by TQCAI** [automl/HPOBench#48]
In BOHB experiments, using `hpolib.benchmarks.synthetic_functions.counting_ones import CountingOnes`, but didn't exist in master bach

**Comment by KEggensperger** [comment]
Hi, these experiments can be found in the development branch of [HPOlib1.5](https://github.com/automl/HPOlib1.5/tree/development). Specifically, the CountingOne function is here: https://github.com/automl/HPOlib1.5/blob/development/hpolib/benchmarks/synthetic_functions/counting_ones.py
