### ISSUE TITLE
SVM Benchmark fidelity space correction

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOBench#50]
The lower limit on the parameter "dataset_fraction" of SVMBenchmark's fidelity space should be set to 0.0. This is because the actual reasonable lower limit on the fraction is a function of the total size, e.g. for a dataset of size 10^6, a dataset fraction of 10^-3 might actually be reasonable. In addition to this, the class initialization code [suggests](https://github.com/automl/HPOlib2/blob/5b20fdc0ebdf133692e84aa442688839e8e69bc3/hpolib/benchmarks/ml/svm_benchmark.py#L76) that a dynamic lower bound is automatically calculated depending on the task at hand and enforced [here](https://github.com/automl/HPOlib2/blob/5b20fdc0ebdf133692e84aa442688839e8e69bc3/hpolib/benchmarks/ml/svm_benchmark.py#L140-L146). Setting the lower limit in the fidelity space to 0.0 allows various applications to use arbitrarily small fraction values depending on the size of the dataset being used.

**Comment by NeoChaos12** [comment]
As of 7f5fa96, a bug in the implementation for the lower bound on the training dataset size has been corrected in addition to the original intent of this issue.

**Comment by PhMueller** [comment]
That's good! Thanks :+1:

**Comment by PhMueller** [comment]
@KEggensperger: I would suggest updating the XGBoostBenchmark accordingly. What do you think?

**Comment by KEggensperger** [comment]
I don't really like allowing a fidelity value that is theoretically impossible, i.e. using 0% of the dataset. This introduces a manual step when automatically running benchmarks. In practice we would then need to manually define a lower bound and we would use the same lower bound for all benchmarks/datasets.

However, I agree that it should be possible to use a lower value if looking individually at large datasets. 

Could we then at least provide a `recommended` lower bound to still allow automated benchmarking?

**Comment by PhMueller** [comment]
I see the point. Setting a value to an illegal one is not optimal, but as Archit said, we already have this lower bound (10 * num classes / total train size) for all datasets. So, even if an "impossible" value is given it is set to the lower bound. 
This is somehow an implementation of this dynamical lower bound per dataset. 
Would that work for you?
Do you mean with "the recommended lower bound" that we set the data fraction in the fidelity space from [0, 1], but the default to something like 0.1?

**Comment by NeoChaos12** [comment]
I agree with Katha that for automated benchmarking processes that try to read the lowest fidelity value and try to systematically increment it, say doubling the value every now and then, a value of 0.0 would indeed be troublesome. One option is to set the value to the lowest positive fraction supported by the language for a float data type, although that comes with its own set of issues, namely clipping. I think what is necessary here is to clarify the intent of the lower and upper bounds of the fidelity space in the documentation itself. Note that the lower bounds are statically generated, which inherently makes it a bad choice for optimizers to directly rely on them for dynamic tasks. I would propose that this, therefore, be made explicitly clear - optimizers should only treat the fidelity lower (and upper) bounds provided by `HPOlib` as "syntactical bounds". Otherwise, the bounds should be dynamically generated based on the task itself.

**Comment by PhMueller** [comment]
#75 closes this issue.
