### ISSUE TITLE
Expose dataset size for SVM/XGB 

### ISSUE THREAD

**Issue by KEggensperger** [automl/HPOBench#74]
Some optimizers would like to know the datasetsize for XGB and SVM, however the containers don't allow to access the array y_train. Would it be possible to make this accessible when using the container? Alternatively, we could add a `get_dataset_size()` method?

**Comment by PhMueller** [comment]
I am not sure if it is easy to get the dataset size from the container, because this would require changes to the interaction between the client and the container.
 
But a simple workaround would be: 

```
from hpobench.util.openml_data_manager import OpenMLHoldoutDataManager

# use the same rng as for the benchmark
rng = 0

dm = OpenMLHoldoutDataManager(openml_task_id=12345, rng=rng)
X_train, y_train, X_val, y_val, X_test, y_test = dm.load()
```

**Comment by KEggensperger** [comment]
Yes, that would work if we know the rng and the dataset id and are accepting to load the dataset again. Let's discuss this in the afternoon.
